{
 "title": "Cardano Node",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Key evolution renew left",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_Forge_metrics_remainingKESPeriods_int * 6 / 24 / 6)",
     "legendFormat": "Days till renew"
    }
   ]
  },
  {
   "title": "KES remaining",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_remainingKESPeriods_int",
     "legendFormat": "KES Remaining"
    }
   ]
  },
  {
   "title": "KES Perioden",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_operationalCertificateExpiryKESPeriod_int",
     "legendFormat": "KES Expiry"
    },
    {
     "expr": "cardano_node_Forge_metrics_currentKESPeriod_int",
     "legendFormat": "KES current"
    }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int",
     "legendFormat": "SlotNo"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int",
     "legendFormat": "Block Height"
    }
   ]
  },
  {
   "title": "Slot in Epoch",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int",
     "legendFormat": "Slot in Epoch"
    }
   ]
  },
  {
   "title": "Node is Block Leader",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "Slot" }
   ],
   "targets": [
    {
     "expr": "cardano_node_Forge_metrics_nodeIsLeader_int",
     "legendFormat": "Node is leader"
    }
   ]
  },
  {
   "title": "Memory Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_mempoolBytes_int / 1024",
     "legendFormat": "Memory KB"
    }
   ]
  },
  {
   "title": "Block-Producer Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns / (1000000000)",
     "legendFormat": "Server Uptime"
    }
   ]
  }
 ]
}